[connections.snowflake]
account = "EODBGZC-KRB90497"
user = "hollingworthsam2000"
password = "YQ&T^,#px9@x2m2"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
